[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit SH110X
    adafruit/Adafruit GFX Library
build_src_filter = +<main.cpp>

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
build_src_filter = +<nano_main.cpp>
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:c3suspicious]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<c3_suspicious.cpp>
lib_deps =
    adafruit/Adafruit SH110X
    adafruit/Adafruit GFX Library

[env:c3bug]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<c3_bug.cpp>
lib_deps =
    adafruit/Adafruit SH110X
    adafruit/Adafruit GFX Library

